"""added audit-log model

Revision ID: 1db30f22d7b9
Revises: b83ac3b8ecad
Create Date: 2026-03-10 17:14:26.350250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1db30f22d7b9'
down_revision: Union[str, None] = 'b83ac3b8ecad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=70), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=180), nullable=True))
    op.add_column('audit_logs', sa.Column('endpoint', sa.String(length=70), nullable=True))
    op.alter_column('audit_logs', 'action',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('posts_ibfk_1'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_ibfk_1'), 'posts', 'users', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('audit_logs', 'endpoint')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    # ### end Alembic commands ###
