"""initial migration

Revision ID: 2c347b65cd69
Revises: 
Create Date: 2025-05-25 11:34:26.188060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c347b65cd69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_ibfk_1'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['post_id'])
    op.drop_constraint(op.f('posts_ibfk_1'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_ibfk_1'), 'posts', 'users', ['user_id'], ['user_id'], onupdate='CASCADE')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_ibfk_1'), 'comments', 'posts', ['post_id'], ['post_id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###
