"""added api-project model

Revision ID: 2e61d7f00bcb
Revises: dea119472ff2
Create Date: 2026-06-17 20:04:43.525533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e61d7f00bcb'
down_revision: Union[str, None] = 'dea119472ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_api_projects_tenant_id'), 'api_projects', ['tenant_id'], unique=False)
    op.add_column('subscriptions', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.create_index('ix_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'tenants', ['tenant_id'], ['tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index('ix_subscriptions_tenant_id', table_name='subscriptions')
    op.drop_column('subscriptions', 'tenant_id')
    op.drop_index(op.f('ix_api_projects_tenant_id'), table_name='api_projects')
    op.drop_table('api_projects')
    # ### end Alembic commands ###
