"""added new column in User model

Revision ID: 31ca77dcf6ea
Revises: 1989dde6fa5a
Create Date: 2025-06-05 14:44:30.806828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ca77dcf6ea'
down_revision: Union[str, None] = '1989dde6fa5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('biography', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'biography')
    # ### end Alembic commands ###
