"""updated user/post models

Revision ID: 4741ccc42f38
Revises: ed3d8fac678a
Create Date: 2025-06-05 18:39:26.269391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4741ccc42f38'
down_revision: Union[str, None] = 'ed3d8fac678a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at', server_default=None)
    op.alter_column('posts', 'updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at', server_default='CURRENT_TIMESTAMP')
    op.alter_column('posts', 'updated_at', server_default='CURRENT_TIMESTAMP')
    # ### end Alembic commands ###
