"""added more r/ship

Revision ID: 53d0fbe7e005
Revises: f5e85a00023c
Create Date: 2026-05-18 21:08:26.452252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53d0fbe7e005'
down_revision: Union[str, None] = 'f5e85a00023c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_invitations', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.add_column('tenant_memberships', sa.Column('max_members', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=True)
    op.add_column('users', sa.Column('active_tenant_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_active_tenant_id'), 'users', ['active_tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['active_tenant_id'], ['tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_active_tenant_id'), table_name='users')
    op.drop_column('users', 'active_tenant_id')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.drop_column('tenant_memberships', 'max_members')
    op.alter_column('tenant_invitations', 'role',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
