"""updated user/post models

Revision ID: 55db7f796b9e
Revises: 4741ccc42f38
Create Date: 2025-06-05 19:26:51.571469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55db7f796b9e'
down_revision: Union[str, None] = '4741ccc42f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at', type_=sa.DateTime(), server_default=None)
    op.alter_column('posts', 'updated_at', type_=sa.DateTime(), server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 
        'updated_at', 
        type_=sa.DateTime(),
        server_default='CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP', 
        nullable=True)
    op.alter_column(
        'posts', 
        'updated_at', 
        type_=sa.DateTime(),
        server_default='CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP', 
        nullable=True)
    # ### end Alembic commands ###
