"""initial_migration_with_2fa

Revision ID: 5b31831f0acf
Revises: 
Create Date: 2026-02-05 15:08:42.494971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b31831f0acf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', 
        sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_2fa_enabled')
    # ### end Alembic commands ###


# Inside your migration file's upgrade() function:
