"""added new models

Revision ID: 946d35eaa5d6
Revises: a196cbad4e57
Create Date: 2026-07-06 11:40:24.941828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946d35eaa5d6'
down_revision: Union[str, None] = 'a196cbad4e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_audits',
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    # 🚀 Added: CASCADE rule to match your multi-tenant tenant deletion logic
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('billing_id'),
    # 🚀 Added: Strict Idempotency defense against double webhook fires
    sa.UniqueConstraint('tenant_id', 'stripe_event_id', name='uq_tenant_stripe_event')
    )
    op.create_index(op.f('ix_billing_audits_event_type'), 'billing_audits', ['event_type'], unique=False)
    op.create_index(op.f('ix_billing_audits_stripe_event_id'), 'billing_audits', ['stripe_event_id'], unique=True)
    op.create_index('ix_billing_audits_tenant_id', 'billing_audits', ['tenant_id'], unique=False)
    
    op.create_table('stripe_checkout_sessions',
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    # 🚀 Added: CASCADE rules for clean lifecycle deletion handling
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkout_id')
    )
    op.create_index(op.f('ix_stripe_checkout_sessions_plan_id'), 'stripe_checkout_sessions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_stripe_checkout_sessions_status'), 'stripe_checkout_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_checkout_sessions_stripe_session_id'), 'stripe_checkout_sessions', ['stripe_session_id'], unique=True)
    op.create_index(op.f('ix_stripe_checkout_sessions_tenant_id'), 'stripe_checkout_sessions', ['tenant_id'], unique=False)
    
    # ✅ FIXED BLOCK FOR UPGRADE:
    # 1. Clear the verified constraint identifier (api_projects_ibfk_1)
    op.drop_constraint('api_projects_ibfk_1', table_name='api_projects', type_='foreignkey')
    
    # 2. Safely swap the index characteristics
    op.drop_index(op.f('ix_api_projects_tenant_id'), table_name='api_projects')
    op.create_index(op.f('ix_api_projects_tenant_id'), 'api_projects', ['tenant_id'], unique=True)
    
    # 3. Re-link the foreign key cleanly using the exact historical name
    op.create_foreign_key(
        'api_projects_ibfk_1',
        source_table='api_projects',
        referent_table='tenants',
        local_cols=['tenant_id'],
        remote_cols=['tenant_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ✅ FIXED BLOCK FOR DOWNGRADE:
    # 1. Drop the constraint blocker first
    op.drop_constraint('api_projects_ibfk_1', table_name='api_projects', type_='foreignkey')
    
    # 2. Revert index properties back to unique=False
    op.drop_index(op.f('ix_api_projects_tenant_id'), table_name='api_projects')
    op.create_index(op.f('ix_api_projects_tenant_id'), 'api_projects', ['tenant_id'], unique=False)
    
    # 3. Restore the original FK structure
    op.create_foreign_key(
        'api_projects_ibfk_1',
        source_table='api_projects',
        referent_table='tenants',
        local_cols=['tenant_id'],
        remote_cols=['tenant_id']
    )

    op.drop_index(op.f('ix_stripe_checkout_sessions_tenant_id'), table_name='stripe_checkout_sessions')
    op.drop_index(op.f('ix_stripe_checkout_sessions_stripe_session_id'), table_name='stripe_checkout_sessions')
    op.drop_index(op.f('ix_stripe_checkout_sessions_status'), table_name='stripe_checkout_sessions')
    op.drop_index(op.f('ix_stripe_checkout_sessions_plan_id'), table_name='stripe_checkout_sessions')
    op.drop_table('stripe_checkout_sessions')
    
    op.drop_index('ix_billing_audits_tenant_id', table_name='billing_audits')
    op.drop_index(op.f('ix_billing_audits_stripe_event_id'), table_name='billing_audits')
    op.drop_index(op.f('ix_billing_audits_event_type'), table_name='billing_audits')
    op.drop_table('billing_audits')
    # ### end Alembic commands ###