"""empty message

Revision ID: a5d63fcd5d0b
Revises: 4977ce6ca74b
Create Date: 2026-02-12 12:02:58.323166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5d63fcd5d0b'
down_revision: Union[str, None] = '4977ce6ca74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=25), nullable=False))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=25), nullable=False))
    # ### end Alembic commands ###
