"""modified models

Revision ID: a66e365173ab
Revises: d1121c97b75f
Create Date: 2026-09-06 11:13:51.025269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a66e365173ab'
down_revision: Union[str, None] = 'd1121c97b75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # (Notice we removed the api_keys block because tenant_id is already gone)
    
    # 1. api_projects: Add index and foreign key
    op.create_index('ix_api_projects_tenant_id', 'api_projects', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'api_projects', 'tenants', ['tenant_id'], ['tenant_id'])
    
    # 2. subscriptions: Drop FK, drop regular index, create unique constraint, recreate FK
    op.drop_constraint('subscriptions_ibfk_1', 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.create_unique_constraint('uq_tenant_id_single', 'subscriptions', ['tenant_id'])
    op.create_foreign_key('subscriptions_ibfk_1', 'subscriptions', 'tenants', ['tenant_id'], ['tenant_id'])
    
    # 3. tenant_memberships & tenants
    op.drop_index(op.f('ix_tenant_memberships_tenant_id'), table_name='tenant_memberships')
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    
    # ### end Alembic commands ###
    
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert tenants and tenant_memberships
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.create_index(op.f('ix_tenant_memberships_tenant_id'), 'tenant_memberships', ['tenant_id'], unique=False)
    
    # Revert subscriptions: Drop FK -> Drop unique constraint -> Recreate index -> Recreate FK
    op.drop_constraint('subscriptions_ibfk_1', 'subscriptions', type_='foreignkey')
    op.drop_constraint('uq_tenant_id_single', 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=True)
    op.create_foreign_key('subscriptions_ibfk_1', 'subscriptions', 'tenants', ['tenant_id'], ['tenant_id'])
    
    # Revert api_projects
    op.drop_constraint(None, 'api_projects', type_='foreignkey')
    op.drop_index('ix_api_projects_tenant_id', table_name='api_projects')
    
    # Revert api_keys: Add column -> Create index -> Create foreign key
    op.add_column('api_keys', sa.Column('tenant_id', mysql.CHAR(length=32), nullable=False))
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_foreign_key(op.f('api_keys_ibfk_1'), 'api_keys', 'tenants', ['tenant_id'], ['tenant_id'])
    
    # ### end Alembic commands ###