"""empty message

Revision ID: ac9cba8cc93d
Revises: 68b343ad75a3
Create Date: 2026-02-12 14:51:50.026934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac9cba8cc93d'
down_revision: Union[str, None] = '68b343ad75a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=75),
               type_=sa.String(length=55),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=55),
               type_=mysql.VARCHAR(length=75),
               existing_nullable=False)
    # ### end Alembic commands ###
