"""updated models

Revision ID: b57f9cd229af
Revises: 2e61d7f00bcb
Create Date: 2026-06-18 07:11:27.477457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b57f9cd229af'
down_revision: Union[str, None] = '2e61d7f00bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('api_keys', sa.Column('is_revoked', sa.Boolean(), nullable=False))
    op.alter_column('api_keys', 'key_prefix',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'api_projects', ['project_id'], ['project_id'])
    op.drop_column('api_keys', 'is_active')
    op.create_unique_constraint(None, 'api_projects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_projects', type_='unique')
    op.add_column('api_keys', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('api_keys', 'is_revoked')
    op.drop_column('api_keys', 'project_id')
    # ### end Alembic commands ###
