"""modified models @

Revision ID: d1121c97b75f
Revises: 5c97b4ada1b9
Create Date: 2026-08-20 17:06:41.783164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1121c97b75f'
down_revision: Union[str, None] = '5c97b4ada1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. api_keys
    try:
        op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_api_keys_revoked_by'), 'api_keys', ['revoked_by'], unique=False)
    except Exception:
        pass
    
    # 2. api_projects (Foreign Key & Index handling)
    try:
        op.drop_constraint("api_projects_ibfk_1", "api_projects", type_="foreignkey")
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_api_projects_tenant_id'), table_name='api_projects')
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_api_projects_tenant_id'), 'api_projects', ['tenant_id'], unique=True)
    except Exception:
        pass
    
    try:
        op.create_foreign_key("api_projects_ibfk_1", "api_projects", "tenants", ["tenant_id"], ["id"])
    except Exception:
        pass

    # 3. credit_logs
    try:
        op.drop_index(op.f('ix_credit_logs_reference_id'), table_name='credit_logs')
    except Exception:
        pass
        
    try:
        op.create_index(op.f('ix_credit_logs_reference_id'), 'credit_logs', ['reference_id'], unique=True)
    except Exception:
        pass
    
    # 4. stripe_checkout_sessions
    op.add_column('stripe_checkout_sessions', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('stripe_checkout_sessions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    try:
        op.create_index(op.f('ix_stripe_checkout_sessions_stripe_subscription_id'), 'stripe_checkout_sessions', ['stripe_subscription_id'], unique=False)
    except Exception:
        pass
    
    # 5. stripe_webhook_events & subscriptions columns
    op.add_column('stripe_webhook_events', sa.Column('processing_error', sa.String(length=1000), nullable=True))
    op.add_column('stripe_webhook_events', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.String(length=255), nullable=False))
    
    # 6. subscriptions (Foreign Key & Index handling)
    try:
        op.drop_constraint("subscriptions_ibfk_1", "subscriptions", type_="foreignkey")
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    except Exception:
        pass
        
    try:
        op.create_index('ix_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=False)
    except Exception:
        pass
    
    try:
        op.create_foreign_key("subscriptions_ibfk_1", "subscriptions", "tenants", ["tenant_id"], ["id"])
    except Exception:
        pass

    try:
        op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    except Exception:
        pass
    
    # 7. tenants
    try:
        op.drop_index(op.f('ix_tenants_created_at'), table_name='tenants')
    except Exception:
        pass
        
    try:
        op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=True)
    except Exception:
        pass
    
    # 8. users columns
    try:
        op.drop_index(op.f('ix_users_created_at'), table_name='users')
    except Exception:
        pass
        
    try:
        op.drop_column('users', 'city')
    except Exception:
        pass
        
    try:
        op.drop_column('users', 'country')
    except Exception:
        pass
        
    try:
        op.drop_column('users', 'biography')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('users', sa.Column('biography', mysql.VARCHAR(length=350), nullable=True))
    except Exception:
        pass
        
    try:
        op.add_column('users', sa.Column('country', mysql.VARCHAR(length=25), nullable=False))
    except Exception:
        pass
        
    try:
        op.add_column('users', sa.Column('city', mysql.VARCHAR(length=25), nullable=False))
    except Exception:
        pass
        
    try:
        op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    except Exception:
        pass
    
    try:
        op.drop_index(op.f('ix_tenants_stripe_customer_id'), table_name='tenants')
    except Exception:
        pass
        
    try:
        op.create_index(op.f('ix_tenants_created_at'), 'tenants', ['created_at'], unique=False)
    except Exception:
        pass
    
    try:
        op.drop_constraint("subscriptions_ibfk_1", "subscriptions", type_="foreignkey")
    except Exception:
        pass
        
    try:
        op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    except Exception:
        pass
        
    try:
        op.drop_index('ix_subscriptions_tenant_id', table_name='subscriptions')
    except Exception:
        pass
        
    try:
        op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=True)
    except Exception:
        pass
    
    try:
        op.create_foreign_key("subscriptions_ibfk_1", "subscriptions", "tenants", ["tenant_id"], ["id"])
    except Exception:
        pass

    try:
        op.drop_column('subscriptions', 'stripe_customer_id')
    except Exception:
        pass
        
    try:
        op.drop_column('stripe_webhook_events', 'retry_count')
    except Exception:
        pass
        
    try:
        op.drop_column('stripe_webhook_events', 'processing_error')
    except Exception:
        pass
    
    try:
        op.drop_index(op.f('ix_stripe_checkout_sessions_stripe_subscription_id'), table_name='stripe_checkout_sessions')
    except Exception:
        pass
        
    try:
        op.drop_column('stripe_checkout_sessions', 'updated_at')
    except Exception:
        pass
        
    try:
        op.drop_column('stripe_checkout_sessions', 'stripe_subscription_id')
    except Exception:
        pass
    
    try:
        op.drop_index(op.f('ix_credit_logs_reference_id'), table_name='credit_logs')
    except Exception:
        pass
        
    try:
        op.create_index(op.f('ix_credit_logs_reference_id'), 'credit_logs', ['reference_id'], unique=False)
    except Exception:
        pass
    
    try:
        op.drop_constraint("api_projects_ibfk_1", "api_projects", type_="foreignkey")
    except Exception:
        pass
        
    try:
        op.drop_index(op.f('ix_api_projects_tenant_id'), table_name='api_projects')
    except Exception:
        pass
        
    try:
        op.create_index(op.f('ix_api_projects_tenant_id'), 'api_projects', ['tenant_id'], unique=False)
    except Exception:
        pass
    
    try:
        op.create_foreign_key("api_projects_ibfk_1", "api_projects", "tenants", ["tenant_id"], ["id"])
    except Exception:
        pass

    try:
        op.drop_index(op.f('ix_api_keys_revoked_by'), table_name='api_keys')
    except Exception:
        pass
        
    try:
        op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    except Exception:
        pass
    # ### end Alembic commands ###

