"""added social login details

Revision ID: dea119472ff2
Revises: 2e973171bd48
Create Date: 2026-06-14 16:20:46.188219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dea119472ff2'
down_revision: Union[str, None] = '2e973171bd48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create an inspector to check current live database columns
    bind = op.get_bind()
    insp = reflection.Inspector.from_engine(bind)
    existing_columns = [col['name'] for col in insp.get_columns('subscriptions')]
    
    # 1. DROP THE FOREIGN KEY FIRST (Only if tenant_id is still around)
    if 'tenant_id' in existing_columns:
        try:
            op.drop_constraint('subscriptions_ibfk_1', 'subscriptions', type_='foreignkey')
        except Exception:
            # Pass if the constraint was already dropped in a previous partial run
            pass
        
        # 2. Now it is safe to drop the old index and old column
        try:
            op.drop_index('ix_subscriptions_tenant_id', table_name='subscriptions')
        except Exception:
            pass
        op.drop_column('subscriptions', 'tenant_id')
    
    # 3. Add your new columns and their structural indexes (Defensive Check)
    if 'owner_id' not in existing_columns:
        op.add_column('subscriptions', sa.Column('owner_id', sa.Uuid(), nullable=False))
        op.create_index(op.f('ix_subscriptions_owner_id'), 'subscriptions', ['owner_id'], unique=False)
    else:
        # If owner_id exists but the index got missed in the crash, create it safely
        existing_indexes = [idx['name'] for idx in insp.get_indexes('subscriptions')]
        if 'ix_subscriptions_owner_id' not in existing_indexes:
            op.create_index(op.f('ix_subscriptions_owner_id'), 'subscriptions', ['owner_id'], unique=False)
    
    # 4. Bind the new foreign key constraint to owner_id
    try:
        op.create_foreign_key('fk_subscriptions_owner_id', 'subscriptions', 'tenants', ['owner_id'], ['tenant_id'])
    except Exception:
        # Pass if it was already established
        pass
    
    # 5. Add your fresh social login profile attributes to the users table
    user_columns = [col['name'] for col in insp.get_columns('users')]
    if 'provider' not in user_columns:
        op.add_column('users', sa.Column('provider', sa.String(length=20), nullable=True))
    if 'provider_id' not in user_columns:
        op.add_column('users', sa.Column('provider_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = reflection.Inspector.from_engine(bind)
    existing_columns = [col['name'] for col in insp.get_columns('subscriptions')]
    
    # 1. Tear down the new foreign key constraint first
    try:
        op.drop_constraint('fk_subscriptions_owner_id', 'subscriptions', type_='foreignkey')
    except Exception:
        pass
    
    # 2. Clear out the new index and new columns safely
    try:
        op.drop_index(op.f('ix_subscriptions_owner_id'), table_name='subscriptions')
    except Exception:
        pass
        
    if 'owner_id' in existing_columns:
        op.drop_column('subscriptions', 'owner_id')
        
    user_columns = [col['name'] for col in insp.get_columns('users')]
    if 'provider_id' in user_columns:
        op.drop_column('users', 'provider_id')
    if 'provider' in user_columns:
        op.drop_column('users', 'provider')
    
    # 3. Re-add your legacy tenant_id columns and index mappings
    if 'tenant_id' not in existing_columns:
        op.add_column('subscriptions', sa.Column('tenant_id', sa.Uuid(), nullable=False))
        op.create_index('ix_subscriptions_tenant_id', 'subscriptions', ['tenant_id'], unique=False)
    
    # 4. Re-establish the original historical foreign key relation mapping
    try:
        op.create_foreign_key('subscriptions_ibfk_1', 'subscriptions', 'tenants', ['tenant_id'], ['tenant_id'])
    except Exception:
        pass
    # ### end Alembic commands ###