"""modified r/ship

Revision ID: e7fff72c1546
Revises: 5cb8ee6358dd
Create Date: 2026-02-09 11:36:24.807875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7fff72c1546'
down_revision: Union[str, None] = '5cb8ee6358dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_ibfk_2'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('comments_ibfk_2'), 'comments', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
