"""updated user model

Revision ID: ed3d8fac678a
Revises: 31ca77dcf6ea
Create Date: 2025-06-05 17:11:42.097100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3d8fac678a'
down_revision: Union[str, None] = '31ca77dcf6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at', server_default=None)
    op.alter_column('posts', 'updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at', server_default='CURRENT_TIMESTAMP')
    op.alter_column('posts', 'updated_at', server_default='CURRENT_TIMESTAMP')
    # ### end Alembic commands ###
